# Generated by Django 4.0.4 on 2022-05-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
