# Generated by Django 4.0.4 on 2022-05-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroApp', '0002_delete_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=300)),
                ('razao_social', models.CharField(max_length=300)),
                ('endereco', models.CharField(max_length=300)),
                ('cnpj', models.CharField(max_length=18)),
                ('contato', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=400)),
                ('custo', models.FloatField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='cadastroApp.categoria')),
                ('fornecedor', models.ManyToManyField(related_name='produtos', to='cadastroApp.fornecedor')),
            ],
        ),
    ]
