# Generated by Django 4.0.4 on 2022-05-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroApp', '0003_fornecedor_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedor',
            old_name='contato',
            new_name='telefones',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='custo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='fornecedor',
        ),
        migrations.CreateModel(
            name='Itens_Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.FloatField()),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fornecedor', to='cadastroApp.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='cadastroApp.produto')),
            ],
        ),
    ]
