# Generated by Django 4.0.4 on 2022-05-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastroApp', '0004_rename_contato_fornecedor_telefones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
